services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # logstash:
  #   container_name: logstash
  #   image: docker.elastic.co/logstash/logstash:8.13.4
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ../chatroom/app.log:/usr/share/logstash/app.log:ro
  #   depends_on:
  #     - elasticsearch
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.13.4
    user: root
    volumes:
      - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
      - ../chatroom/app.log:/var/log/app.log:ro
    depends_on:
      - elasticsearch

volumes:
  grafana-storage:
