# config/local.yaml

env: "local"
logging: "DEBUG"
postgres_connection_string: "postgres://postgres:admin@localhost:5432/mychat"
mongo_connection_string: ""
index_file_path: "index.html"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s